---
title: "HOG feature"
author: "Joo Kim"
date: "2/28/2018"
output: html_document
---


```{r}
source("http://bioconductor.org/biocLite.R")
biocLite()
biocLite("EBImage")
library("EBImage")

setwd("/Users/jookim/Documents/GitHub/project-2-predictive-modelling-group-2/")

experiment_dir <- "../data/pets/"
img_train_dir  <- paste(experiment_dir, "train/", sep = "")
hog_feature_train_dir  <- "../output/"

label_train <- read.table(paste(experiment_dir, "train_label.txt", sep = ""), header = F)
label_train <- as.numeric(unlist(label_train) == "cat")
n_files <- length(list.files(img_train_dir))
```

Creating a balanced dataset using SMOTE

```{r}
library(DMwR)

```


Cropping and resizing images

```{r}
train_data <- list()
cropped <- list()
resized <- list()

for (i in 1:n_files){
    path <- paste(img_train_dir,"pet", i, ".jpg", sep = "")
    train_data[[i]] <- readImage(path)
    cropped[[i]] <- if(ncol(train_data[[i]]) > nrow(train_data[[i]])){
      cropImage(train_data[[i]], nrow(train_data[[i]]) - 1, nrow(train_data[[i]]) - 1,
                type = "equal_spaced")
      } else {
        cropImage(train_data[[i]], ncol(train_data[[i]]) - 1, ncol(train_data[[i]]) - 1,
                  type = "equal_spaced")
        }
    resized[[i]] <- resizeImage(cropped[[i]], 64, 64, method = "bilinear")
}
```

HOG extraction 

```{r}
feature.hog <- function(img_train_dir, data_name, set_name, export = T, cell, orientation){

# Read, crop, and resize images   
    
train_data <- list()
cropped <- list()
resized <- list()

for (i in 1:sample_files){
    path <- paste(sample_dir,"pet", i, ".jpg", sep = "")
    train_data[[i]] <- readImage(path)
    cropped[[i]] <- if(ncol(train_data[[i]]) > nrow(train_data[[i]])){
      cropImage(train_data[[i]], nrow(train_data[[i]]) - 1, nrow(train_data[[i]]) - 1,
                type = "equal_spaced")
      } else {
        cropImage(train_data[[i]], ncol(train_data[[i]]) - 1, ncol(train_data[[i]]) - 1,
                  type = "equal_spaced")
        }
    resized[[i]] <- resizeImage(cropped[[i]], 64, 64, method = "bilinear")
}
  
# extract hog feature (cell and orientation numbers may be changed with tuning)
hog <- matrix(NA, nrow = n_files, ncol = 192)
for (i in 1:n_files){
    hog <- matrix(HOG(resized[[i]], cells = 8, orientations = 8), 
                  nrow = n_files, ncol = 192)
  }

# output constructed features (NOT SURE WHAT THIS IS DOING)
if(export){
  write.table(hog, 
              file = paste0("../output/hog_feature_", cell, orientation, "_", 
                            data_name, "_", set_name, ".csv"), row.names = F, 
              col.names = F, sep = ",")
  }
  
  return(hog)

}

```

Organize features & create CSV with pets label 

```{r}
write.csv(hog, file = "../output/hog.csv")
pets_hog <- read.csv("../output/hog.csv", row.names = 1)

label_train_sample <- read.table(paste(experiment_dir, 
                                       "train_label.txt", sep = ""), header = F)
label_train_sample <- as.numeric(unlist(label_train_sample) == "cat")

pets_hog$pet <- label_train_sample
write.csv(pets_hog, file = "../output/hog_withlabel.csv")
hog_train_data <- read.csv("../output/hog_withlabel.csv", row.names = 1)
hog_train_data$pet <- factor(hog_train_data$pet, levels = c(0:1), 
                             labels = c("dog", "cat"))
hog_train_data <- hog_train_data[, sort(names(hog_train_data))]

hog_train_data2 <- hog_train_data[1:1800, ]
hog_test_data <- hog_train_data[1801:2000, ]

```

Test on randomForest 

```{r train.R}
library(randomForest)
rf_fit <- randomForest(hog_train_data2[, -1], hog_train_data2[, 1], 
                          ntree = 500, mtry = 50)
yhat_rf <- predict(rf_fit, hog_test_data, type = "class")
table_rf <- table(hog_test_data[, 1], yhat_rf)
table_rf
sum(diag(table_rf)) / sum(table_rf) 
```


HOG parameter tuning (NOT DONE)

```{r}
library(caret)

label = read.csv('../data/training_set/label_train.csv', header = T)

or <- c(6, 8, 10)
cell <- c(6, 7, 8)

library(OpenImageR)

 train_data<-list()
 img_dir<-"../data/training_set/images"
 
 
 for (i in 1:3000){
   n<-nchar(as.character(i))
   path<-paste0(img_dir,"/img_",paste(rep(0,4-n),collapse=""),i,".jpg")
   train_data[[i]]<-readImage(path)
 }

accuracy <- matrix(NA, nrow = length(cell), ncol = length(or))
colnames(accuracy) <- paste("orientation", or)
rownames(accuracy) <- paste("cells", cell)

  for(j in 1:length(cell)){
    for(h in 1: length(or)){
      
      hog <- matrix(NA, nrow = length(sample_files), ncol = 3 * length(cell) * length(or))
      for (i in 1:sample_files){
        hog <- HOG(train_data[[i]], cells = cell[j], orientations = or[h])
      }
      
      #write.csv(hog,file=paste0("hog",cell[j],or[h],".csv"))
      #write.table(hog,file=paste0("hog",cell[j],or[h],".csv"),row.names = F,col.names = F,sep=",")
      
      df <- hog
      set.seed(42)
      df_complete = cbind(label, df) # Combine the dataframe and label
      df_complete = df_complete[, -c(1)] # Delete the Useless Column 
      colnames(df_complete)[1] = c('Label') # Rename the Column
      df_complete$Label = as.factor(df_complete$Label) # Make the Label as factor
      dpart = createDataPartition(df_complete$Label, p = 0.2, list = F) #Balanced Partition
      df_test = df_complete[dpart, ] # test set
      df_train = df_complete[-dpart, ] # training set

      lr.fit = multinom(Label~., data = df_train, MaxNWts=16000)
      accuracy[j,h] <-1- mean(predict(lr.fit, df_test) != df_test$Label)

    }
    
  }

save(accuracy,file="../output/accuracy.Rdata")
```





